# Generated by Django 4.2.11 on 2026-02-26 02:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='applicant_user',
            field=models.ForeignKey(blank=True, help_text='User who applied (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='job',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='User who posted the job', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to=settings.AUTH_USER_MODEL),
        ),
    ]
